### ISSUE TITLE
Allow for flagging or opening issues for failing upgrades

### ISSUE THREAD

**Issue by kchare** [capitalone/edgetest-hub#28]
The current implementation of `edgetest-hub` supports a plugin with an action for updating the environment when the new environment test [passes](https://github.com/capitalone/edgetest-hub/blob/dev/edgetest_hub/plugin.py#L209), but not when the change in the versions has caused a failure. This could be useful for flagging breaking changes in upstream libraries that may otherwise go unnoticed.

The general use case that brought this to mind is a desire to know when dependencies have been updated that would break the CI if installing a package from `main`. This can manually be handled by running `edgetest` locally/through CI before releasing new features in a library being tracked by `edgetest`, but this may not occur often for software that is in maintenance-mode and not under active development. 

My thought was that the plugin could handle the case where `testers[-1].status == False` by opening an issue in the repository with some of the e.g. report metadata. Maintainers would then be alerted to breaking changes while still ensuring that the pins are correct if installing from `main`. They could then decide whether updating the package is necessary and the extent of the issues. This could also be configured via the optional configuration parameters to only happen in some cases.

**Comment by fdosani** [comment]
I like this idea. @ak-gupta any thoughts on this?

@kchare happy to accept a PR too if you had time. No pressure, I was going to spend time time in the next week working on some open issues.
